### ISSUE TITLE
Small reviews on  chapter  7:  Measuring population structure using Fst

### ISSUE THREAD

**Issue by EirSkou** [MPI-EVA-Archaeogenetics/comp_human_adna_book#16]
1.  [7.1.1] "Example: With  N=100 (haploid individuals), we might consider a genetic locus with two alleles A and B, and in the parent generation, say, 50 individuals carried allele B, and 50 carried allele B. " --> Change one of the `B` to `A`

2.  [7.1.1] "As a statistical process, this amounts to a binomial process, where the N offspring individuals are drawn" --> add "with replacement".

3. [7.2] When you define "REPO=/path/to/community-archive/2012_PattersonGenetics", maybe add a note or a link o how to download a poseidon package.

Other than that, the chapter is awesome!

**Comment by stschiff** [comment]
Great. I have added all of these points. Thanks a lot!
