### ISSUE TITLE
Hackathon Review: 2 Genotype and context data management with Poseidon

### ISSUE THREAD

**Issue by EleniSef** [MPI-EVA-Archaeogenetics/comp_human_adna_book#17]
Maybe you can take a look at these issues:

- Author list: **CL**emens has the first two letters capital
- Poseidon is an entire ecosystem build : it should be "Poseidon is an entire ecosystem **built**"
- In this sentence: _"It includes sample-wise context information like spatio-temporal origin and genetic data quality in the .janno-file, literature in the .bib, and pointers to sequencing data in the .ssf file."_  Maybe have all with the -file ending (in .bib is missing) or remove it from all to correspond to the naming of a poseidon package. 
- International Nucleotide Sequence Database Collaboration (INSDC) link: the link (ihttps://www.insdc.org) does not work - has an i in the beginning. 
- Trident Forge examples: _"To include all individuals in a Poseidon package, use * to surround the package title.*2019_Jeong_InnerEurasia*"_ I think it would make more sense to put the examples in (e.g. *2019_Jeong_InnerEurasia*) instead of a full stop before. 
- Trident forge groups: "_To include certain group(s) from a Poseidon package, simply add them to the -f query. No specific markers are required. Russia_HG_Karelia_" Here it would make sense to also mention that when you only want specific groups you don't need to add the package name of the group as it is for individuals below, as this will include the whole package. 
- forgeFile: I would move this option to package forging because it's also super useful there and not only when making a pca. 
- 2.3 Contributing to the community archive: in this point "Git LFS has to be installed (see here) **and and** configured for your user with git lfs install": you have 2 and. 
- There are random commas that can be omitted throughout the text.
- I am not sure if I would keep the dog meme picture, is difficult to understand its purpose and a bit weird.

**Comment by stschiff** [comment]
Very helpful, thanks a lot @EleniSef. I may tackle that, as @nevrome is not going to be able to deal with this very soon.

**Comment by stschiff** [comment]
Super, I've gone through all points and done the necessary changes.
